package io.continual.mcp

GET		/authorize							McpEndpoints.authorize
GET		/callback							McpEndpoints.callback
GET		/token								McpEndpoints.token
POST	/token								McpEndpoints.postToken
POST	/register							McpEndpoints.registerClient
GET		/.well-known/oauth-authorization-server		McpEndpoints.oauthAuthorizationServerMetadata
GET		/.well-known/oauth-protected-resource/mcp	McpEndpoints.oauthProtectedResourceMetadata

GET		/mcp			McpEndpoints.getMcp
POST	/mcp			McpEndpoints.postMcpStateless
POST	/mcp/{sessionId}			McpEndpoints.postMcp
